server:
  port: 8081
  servlet:
    context-path: /api/community

spring:
  application:
    name: ms-communities
  jpa:
    show-sql: false

  kafka:
    template:
      default-topic: "bleiny_community_topic"
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: communities-events-listener-group
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8761/eureka